---
- name: install nginx
  become: yes
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: remove default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: configure nginx backend
  become: yes
  template:
    src: roles/nginx/templates/backendconf.j2
    dest: /etc/nginx/sites-available/default

- name: create symlink for backendconf
  become: yes
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: create main index page
  become: yes
  template:
    src: roles/nginx/templates/hello.j2
    dest: /var/www/html/index.html

- name: create page for test
  copy:
    dest: /var/www/html/test.html
    content: "Being served by {{ ansible_hostname }}"
  notify: restart nginx

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted

- name: tests
  block:
    - name: get test page
      uri:
        url: "http://{{ ansible_host }}/test.html"
        method: GET
        return_content: yes
      register: page
    - debug:
        var: page.x_who